# Generated by Django 4.2.2 on 2023-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tecnologia', models.CharField(max_length=50)),
                ('fecha_creado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
